# adapted from 
# https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/compose.yaml
x-shared-vars:
  nc-domain: &nc-domain nextcloud.pembau.art
  collabora-domain: &collabora-domain collabora.nextcloud.pembau.art
  lenc-email: &lenc-email admin@pembau.art

secrets:
  db_root:
    file: creds/db_root
  db_user:
    file: creds/db_user
  nc_admin:
    file: creds/nc_admin

services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DISABLE_UPGRADE_BACKUP: "1"
    env_file:
      - db.env
    secrets:
      - db_root
      - db_user

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  app:
    image: nextcloud:30-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      MYSQL_HOST: db
      REDIS_HOST: redis
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nc_admin
      NEXTCLOUD_HOSTNAME: *nc-domain
      NEXTCLOUD_TRUSTED_DOMAINS: *nc-domain
      PHP_OPCACHE_MEMORY_CONSUMPTION: 256
      VIRTUAL_HOST: *nc-domain
      LETSENCRYPT_HOST: *nc-domain
      LETSENCRYPT_EMAIL: *lenc-email
    env_file:
      - db.env
    secrets:
      - db_user
      - nc_admin
    depends_on:
      - db
      - redis
      # Added proxy container dependency below. 
      # It is unclear on when or why it happens, but sometimes NC manages to start before the proxy 
      #  and it breaks for whatever weird reason resulting in the need of manual proxy container restart.
      - proxy
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:30-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  collabora:
    build: ./collabora
    restart: always
    environment:
      TZ: Europe/Vienna
      dictionaries: de_DE
      server_name: *collabora-domain
      extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:ssl.sts.enabled=true
      VIRTUAL_HOST: *collabora-domain
      LETSENCRYPT_HOST: *collabora-domain
      LETSENCRYPT_EMAIL: *lenc-email
    networks:
      - proxy-tier
    cap_add:
      - MKNOD
    tty: true

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      TRUST_DOWNSTREAM_PROXY: "false"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - certs:/etc/nginx/certs:ro,z
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - dhparam:/etc/nginx/dhparam:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      DEFAULT_EMAIL: *lenc-email
    volumes:
      - certs:/etc/nginx/certs:z
      - acme:/etc/acme.sh:z
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

# self signed
#  omgwtfssl:
#    image: paulczar/omgwtfssl
#    restart: "no"
#    volumes:
#      - certs:/certs
#    environment:
#      SSL_SUBJECT: servhostname.local
#      CA_SUBJECT: my@example.com
#      SSL_KEY: /certs/servhostname.local.key
#      SSL_CSR: /certs/servhostname.local.csr
#      SSL_CERT: /certs/servhostname.local.crt
#    networks:
#      - proxy-tier

volumes:
  db:
  redis:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:
  dhparam:

networks:
  proxy-tier:
